const magazines = [
    {
        title: "Tech Innovations",
        date: "January 2024",
        cover: "img/tech.jpg",
        description: "Exploring the latest in technology and innovation. Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus enim libero explicabo sit, aperiam sed dolores pariatur ea asperiores dolore, reiciendis consequuntur maiores perspiciatis vel perferendis nobis, exercitationem excepturi magni Labore quam quis cumque doloribus expedita hic aspernatur in? Voluptatum molestiae, modi aperiam veritatis odio dolore rerum animi voluptas quo ducimus expedita, quod delectus quidem magni. Ea autem facere consectetu Perferendis magni, assumenda sequi, similique tempore odit nulla suscipit quo molestiae consectetur dicta repudiandae aliquam, soluta facere vero! Eligendi, tempore enim repellendus impedit sunt quaerat quam illum minus officia vero Tempora corporis quas ab illum, ipsam dolore expedita labore! Perferendis consectetur a necessitatibus, est dicta, provident maxime ipsam aut rerum autem voluptate accusamus! Ex illum inventore saepe, molestias autem doloremqueIpsam corporis deserunt tempora optio nostrum officia tempore mollitia totam impedit numquam consectetur, vel harum nisi blanditiis, porro sint maxime ipsum. Ad suscipit perferendis ea assumenda exercitationem enim eum dolorumSed voluptate ut laudantium, ducimus fugiat, expedita aut, incidunt tenetur aliquam alias ipsa. Atque, iste a eius, aspernatur vero, sunt perferendis natus eligendi accusantium praesentium quo id expedita soluta molestiasCorrupti quisquam dignissimos beatae dolores eligendi exercitationem sapiente cum ratione qui? Facere commodi quis esse aperiam iste consectetur nisi, ab beatae suscipit voluptate omnis sapiente rerum aspernatur nihil? Hic, voluptatibusMagni, perspiciatis odit! Dignissimos ullam porro eligendi architecto tenetur, cum placeat? Vitae, deserunt totam reiciendis eligendi neque aliquid quos voluptates odit eius. Expedita explicabo libero veritatis id soluta? Obcaecati, voluptatem Mollitia odit fuga quis eos necessitatibus alias commodi ducimus aliquid, eveniet in cumque sint nihil. Aperiam repudiandae consequatur quis iste saepe incidunt mollitia modi debitis illum corrupti nesciunt, atquQuaerat rerum odit, adipisci ipsam a molestiae totam amet nisi omnis voluptatum deleniti quia hic dolore corrupti tenetur veniam quos? Aliquid voluptatibus facilis excepturi modi non in neque deserunt a Sed aut consequuntur fugiat earum, ipsam dolorem autem architecto voluptatibus error, officia neque at incidunt perferendis nobis officiis labore esse veritatis cumque tempora laboriosam ratione, expedita quasi eos. Soluta, dolore Labore nemo ea, commodi ducimus veritatis veniam asperiores expedita porro corrupti consequatur sed! Cum provident vero alias molestias repudiandae iure, asperiores, maxime cupiditate ullam similique reprehenderit. Aut corporis ipsa tempora!"
    },
    {
        title: "Health & Wellness",
        date: "February 2024",
        cover: "img/health.jpeg",
        description: "A guide to living a healthier life. Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus enim libero explicabo sit, aperiam sed dolores pariatur ea asperiores dolore, reiciendis consequuntur maiores perspiciatis vel perferendis nobis, exercitationem excepturi magni Labore quam quis cumque doloribus expedita hic aspernatur in? Voluptatum molestiae, modi aperiam veritatis odio dolore rerum animi voluptas quo ducimus expedita, quod delectus quidem magni. Ea autem facere consectetu Perferendis magni, assumenda sequi, similique tempore odit nulla suscipit quo molestiae consectetur dicta repudiandae aliquam, soluta facere vero! Eligendi, tempore enim repellendus impedit sunt quaerat quam illum minus officia vero Tempora corporis quas ab illum, ipsam dolore expedita labore! Perferendis consectetur a necessitatibus, est dicta, provident maxime ipsam aut rerum autem voluptate accusamus! Ex illum inventore saepe, molestias autem doloremqueIpsam corporis deserunt tempora optio nostrum officia tempore mollitia totam impedit numquam consectetur, vel harum nisi blanditiis, porro sint maxime ipsum. Ad suscipit perferendis ea assumenda exercitationem enim eum dolorumSed voluptate ut laudantium, ducimus fugiat, expedita aut, incidunt tenetur aliquam alias ipsa. Atque, iste a eius, aspernatur vero, sunt perferendis natus eligendi accusantium praesentium quo id expedita soluta molestiasCorrupti quisquam dignissimos beatae dolores eligendi exercitationem sapiente cum ratione qui? Facere commodi quis esse aperiam iste consectetur nisi, ab beatae suscipit voluptate omnis sapiente rerum aspernatur nihil? Hic, voluptatibusMagni, perspiciatis odit! Dignissimos ullam porro eligendi architecto tenetur, cum placeat? Vitae, deserunt totam reiciendis eligendi neque aliquid quos voluptates odit eius. Expedita explicabo libero veritatis id soluta? Obcaecati, voluptatem Mollitia odit fuga quis eos necessitatibus alias commodi ducimus aliquid, eveniet in cumque sint nihil. Aperiam repudiandae consequatur quis iste saepe incidunt mollitia modi debitis illum corrupti nesciunt, atquQuaerat rerum odit, adipisci ipsam a molestiae totam amet nisi omnis voluptatum deleniti quia hic dolore corrupti tenetur veniam quos? Aliquid voluptatibus facilis excepturi modi non in neque deserunt a Sed aut consequuntur fugiat earum, ipsam dolorem autem architecto voluptatibus error, officia neque at incidunt perferendis nobis officiis labore esse veritatis cumque tempora laboriosam ratione, expedita quasi eos. Soluta, dolore Labore nemo ea, commodi ducimus veritatis veniam asperiores expedita porro corrupti consequatur sed! Cum provident vero alias molestias repudiandae iure, asperiores, maxime cupiditate ullam similique reprehenderit. Aut corporis ipsa tempora!"
    },
    {
        title: "Travel Adventures",
        date: "March 2024",
        cover: "img/travel.jpeg",
        description: "Discover the world's most beautiful destinations. Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus enim libero explicabo sit, aperiam sed dolores pariatur ea asperiores dolore, reiciendis consequuntur maiores perspiciatis vel perferendis nobis, exercitationem excepturi magni Labore quam quis cumque doloribus expedita hic aspernatur in? Voluptatum molestiae, modi aperiam veritatis odio dolore rerum animi voluptas quo ducimus expedita, quod delectus quidem magni. Ea autem facere consectetu Perferendis magni, assumenda sequi, similique tempore odit nulla suscipit quo molestiae consectetur dicta repudiandae aliquam, soluta facere vero! Eligendi, tempore enim repellendus impedit sunt quaerat quam illum minus officia vero Tempora corporis quas ab illum, ipsam dolore expedita labore! Perferendis consectetur a necessitatibus, est dicta, provident maxime ipsam aut rerum autem voluptate accusamus! Ex illum inventore saepe, molestias autem doloremqueIpsam corporis deserunt tempora optio nostrum officia tempore mollitia totam impedit numquam consectetur, vel harum nisi blanditiis, porro sint maxime ipsum. Ad suscipit perferendis ea assumenda exercitationem enim eum dolorumSed voluptate ut laudantium, ducimus fugiat, expedita aut, incidunt tenetur aliquam alias ipsa. Atque, iste a eius, aspernatur vero, sunt perferendis natus eligendi accusantium praesentium quo id expedita soluta molestiasCorrupti quisquam dignissimos beatae dolores eligendi exercitationem sapiente cum ratione qui? Facere commodi quis esse aperiam iste consectetur nisi, ab beatae suscipit voluptate omnis sapiente rerum aspernatur nihil? Hic, voluptatibusMagni, perspiciatis odit! Dignissimos ullam porro eligendi architecto tenetur, cum placeat? Vitae, deserunt totam reiciendis eligendi neque aliquid quos voluptates odit eius. Expedita explicabo libero veritatis id soluta? Obcaecati, voluptatem Mollitia odit fuga quis eos necessitatibus alias commodi ducimus aliquid, eveniet in cumque sint nihil. Aperiam repudiandae consequatur quis iste saepe incidunt mollitia modi debitis illum corrupti nesciunt, atquQuaerat rerum odit, adipisci ipsam a molestiae totam amet nisi omnis voluptatum deleniti quia hic dolore corrupti tenetur veniam quos? Aliquid voluptatibus facilis excepturi modi non in neque deserunt a Sed aut consequuntur fugiat earum, ipsam dolorem autem architecto voluptatibus error, officia neque at incidunt perferendis nobis officiis labore esse veritatis cumque tempora laboriosam ratione, expedita quasi eos. Soluta, dolore Labore nemo ea, commodi ducimus veritatis veniam asperiores expedita porro corrupti consequatur sed! Cum provident vero alias molestias repudiandae iure, asperiores, maxime cupiditate ullam similique reprehenderit. Aut corporis ipsa tempora!"

    },
    {
        title: "Culinary Delights",
        date: "April 2024",
        cover: "img/dining.jpg",
        description: "A journey through the world of food. Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus enim libero explicabo sit, aperiam sed dolores pariatur ea asperiores dolore, reiciendis consequuntur maiores perspiciatis vel perferendis nobis, exercitationem excepturi magni Labore quam quis cumque doloribus expedita hic aspernatur in? Voluptatum molestiae, modi aperiam veritatis odio dolore rerum animi voluptas quo ducimus expedita, quod delectus quidem magni. Ea autem facere consectetu Perferendis magni, assumenda sequi, similique tempore odit nulla suscipit quo molestiae consectetur dicta repudiandae aliquam, soluta facere vero! Eligendi, tempore enim repellendus impedit sunt quaerat quam illum minus officia vero Tempora corporis quas ab illum, ipsam dolore expedita labore! Perferendis consectetur a necessitatibus, est dicta, provident maxime ipsam aut rerum autem voluptate accusamus! Ex illum inventore saepe, molestias autem doloremqueIpsam corporis deserunt tempora optio nostrum officia tempore mollitia totam impedit numquam consectetur, vel harum nisi blanditiis, porro sint maxime ipsum. Ad suscipit perferendis ea assumenda exercitationem enim eum dolorumSed voluptate ut laudantium, ducimus fugiat, expedita aut, incidunt tenetur aliquam alias ipsa. Atque, iste a eius, aspernatur vero, sunt perferendis natus eligendi accusantium praesentium quo id expedita soluta molestiasCorrupti quisquam dignissimos beatae dolores eligendi exercitationem sapiente cum ratione qui? Facere commodi quis esse aperiam iste consectetur nisi, ab beatae suscipit voluptate omnis sapiente rerum aspernatur nihil? Hic, voluptatibusMagni, perspiciatis odit! Dignissimos ullam porro eligendi architecto tenetur, cum placeat? Vitae, deserunt totam reiciendis eligendi neque aliquid quos voluptates odit eius. Expedita explicabo libero veritatis id soluta? Obcaecati, voluptatem Mollitia odit fuga quis eos necessitatibus alias commodi ducimus aliquid, eveniet in cumque sint nihil. Aperiam repudiandae consequatur quis iste saepe incidunt mollitia modi debitis illum corrupti nesciunt, atquQuaerat rerum odit, adipisci ipsam a molestiae totam amet nisi omnis voluptatum deleniti quia hic dolore corrupti tenetur veniam quos? Aliquid voluptatibus facilis excepturi modi non in neque deserunt a Sed aut consequuntur fugiat earum, ipsam dolorem autem architecto voluptatibus error, officia neque at incidunt perferendis nobis officiis labore esse veritatis cumque tempora laboriosam ratione, expedita quasi eos. Soluta, dolore Labore nemo ea, commodi ducimus veritatis veniam asperiores expedita porro corrupti consequatur sed! Cum provident vero alias molestias repudiandae iure, asperiores, maxime cupiditate ullam similique reprehenderit. Aut corporis ipsa tempora!"
    },
    {
        title: "Fashion Trends",
        date: "May 2024",
        cover: "img/fashion.jpeg",
        description: "Stay updated with the latest fashion trends. Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus enim libero explicabo sit, aperiam sed dolores pariatur ea asperiores dolore, reiciendis consequuntur maiores perspiciatis vel perferendis nobis, exercitationem excepturi magni Labore quam quis cumque doloribus expedita hic aspernatur in? Voluptatum molestiae, modi aperiam veritatis odio dolore rerum animi voluptas quo ducimus expedita, quod delectus quidem magni. Ea autem facere consectetu Perferendis magni, assumenda sequi, similique tempore odit nulla suscipit quo molestiae consectetur dicta repudiandae aliquam, soluta facere vero! Eligendi, tempore enim repellendus impedit sunt quaerat quam illum minus officia vero Tempora corporis quas ab illum, ipsam dolore expedita labore! Perferendis consectetur a necessitatibus, est dicta, provident maxime ipsam aut rerum autem voluptate accusamus! Ex illum inventore saepe, molestias autem doloremqueIpsam corporis deserunt tempora optio nostrum officia tempore mollitia totam impedit numquam consectetur, vel harum nisi blanditiis, porro sint maxime ipsum. Ad suscipit perferendis ea assumenda exercitationem enim eum dolorumSed voluptate ut laudantium, ducimus fugiat, expedita aut, incidunt tenetur aliquam alias ipsa. Atque, iste a eius, aspernatur vero, sunt perferendis natus eligendi accusantium praesentium quo id expedita soluta molestiasCorrupti quisquam dignissimos beatae dolores eligendi exercitationem sapiente cum ratione qui? Facere commodi quis esse aperiam iste consectetur nisi, ab beatae suscipit voluptate omnis sapiente rerum aspernatur nihil? Hic, voluptatibusMagni, perspiciatis odit! Dignissimos ullam porro eligendi architecto tenetur, cum placeat? Vitae, deserunt totam reiciendis eligendi neque aliquid quos voluptates odit eius. Expedita explicabo libero veritatis id soluta? Obcaecati, voluptatem Mollitia odit fuga quis eos necessitatibus alias commodi ducimus aliquid, eveniet in cumque sint nihil. Aperiam repudiandae consequatur quis iste saepe incidunt mollitia modi debitis illum corrupti nesciunt, atquQuaerat rerum odit, adipisci ipsam a molestiae totam amet nisi omnis voluptatum deleniti quia hic dolore corrupti tenetur veniam quos? Aliquid voluptatibus facilis excepturi modi non in neque deserunt a Sed aut consequuntur fugiat earum, ipsam dolorem autem architecto voluptatibus error, officia neque at incidunt perferendis nobis officiis labore esse veritatis cumque tempora laboriosam ratione, expedita quasi eos. Soluta, dolore Labore nemo ea, commodi ducimus veritatis veniam asperiores expedita porro corrupti consequatur sed! Cum provident vero alias molestias repudiandae iure, asperiores, maxime cupiditate ullam similique reprehenderit. Aut corporis ipsa tempora!"
    },
    {
        title: "Home Decor",
        date: "June 2024",
        cover: "img/home.jpeg",
        description: "Tips and tricks for beautiful home styling. Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus enim libero explicabo sit, aperiam sed dolores pariatur ea asperiores dolore, reiciendis consequuntur maiores perspiciatis vel perferendis nobis, exercitationem excepturi magni Labore quam quis cumque doloribus expedita hic aspernatur in? Voluptatum molestiae, modi aperiam veritatis odio dolore rerum animi voluptas quo ducimus expedita, quod delectus quidem magni. Ea autem facere consectetu Perferendis magni, assumenda sequi, similique tempore odit nulla suscipit quo molestiae consectetur dicta repudiandae aliquam, soluta facere vero! Eligendi, tempore enim repellendus impedit sunt quaerat quam illum minus officia vero Tempora corporis quas ab illum, ipsam dolore expedita labore! Perferendis consectetur a necessitatibus, est dicta, provident maxime ipsam aut rerum autem voluptate accusamus! Ex illum inventore saepe, molestias autem doloremqueIpsam corporis deserunt tempora optio nostrum officia tempore mollitia totam impedit numquam consectetur, vel harum nisi blanditiis, porro sint maxime ipsum. Ad suscipit perferendis ea assumenda exercitationem enim eum dolorumSed voluptate ut laudantium, ducimus fugiat, expedita aut, incidunt tenetur aliquam alias ipsa. Atque, iste a eius, aspernatur vero, sunt perferendis natus eligendi accusantium praesentium quo id expedita soluta molestiasCorrupti quisquam dignissimos beatae dolores eligendi exercitationem sapiente cum ratione qui? Facere commodi quis esse aperiam iste consectetur nisi, ab beatae suscipit voluptate omnis sapiente rerum aspernatur nihil? Hic, voluptatibusMagni, perspiciatis odit! Dignissimos ullam porro eligendi architecto tenetur, cum placeat? Vitae, deserunt totam reiciendis eligendi neque aliquid quos voluptates odit eius. Expedita explicabo libero veritatis id soluta? Obcaecati, voluptatem Mollitia odit fuga quis eos necessitatibus alias commodi ducimus aliquid, eveniet in cumque sint nihil. Aperiam repudiandae consequatur quis iste saepe incidunt mollitia modi debitis illum corrupti nesciunt, atquQuaerat rerum odit, adipisci ipsam a molestiae totam amet nisi omnis voluptatum deleniti quia hic dolore corrupti tenetur veniam quos? Aliquid voluptatibus facilis excepturi modi non in neque deserunt a Sed aut consequuntur fugiat earum, ipsam dolorem autem architecto voluptatibus error, officia neque at incidunt perferendis nobis officiis labore esse veritatis cumque tempora laboriosam ratione, expedita quasi eos. Soluta, dolore Labore nemo ea, commodi ducimus veritatis veniam asperiores expedita porro corrupti consequatur sed! Cum provident vero alias molestias repudiandae iure, asperiores, maxime cupiditate ullam similique reprehenderit. Aut corporis ipsa tempora!"
    },
    {
        title: "Fitness Guide",
        date: "July 2024",
        cover: "img/fitness.jpeg",
        description: "Your ultimate guide to staying fit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus enim libero explicabo sit, aperiam sed dolores pariatur ea asperiores dolore, reiciendis consequuntur maiores perspiciatis vel perferendis nobis, exercitationem excepturi magni Labore quam quis cumque doloribus expedita hic aspernatur in? Voluptatum molestiae, modi aperiam veritatis odio dolore rerum animi voluptas quo ducimus expedita, quod delectus quidem magni. Ea autem facere consectetu Perferendis magni, assumenda sequi, similique tempore odit nulla suscipit quo molestiae consectetur dicta repudiandae aliquam, soluta facere vero! Eligendi, tempore enim repellendus impedit sunt quaerat quam illum minus officia vero Tempora corporis quas ab illum, ipsam dolore expedita labore! Perferendis consectetur a necessitatibus, est dicta, provident maxime ipsam aut rerum autem voluptate accusamus! Ex illum inventore saepe, molestias autem doloremqueIpsam corporis deserunt tempora optio nostrum officia tempore mollitia totam impedit numquam consectetur, vel harum nisi blanditiis, porro sint maxime ipsum. Ad suscipit perferendis ea assumenda exercitationem enim eum dolorumSed voluptate ut laudantium, ducimus fugiat, expedita aut, incidunt tenetur aliquam alias ipsa. Atque, iste a eius, aspernatur vero, sunt perferendis natus eligendi accusantium praesentium quo id expedita soluta molestiasCorrupti quisquam dignissimos beatae dolores eligendi exercitationem sapiente cum ratione qui? Facere commodi quis esse aperiam iste consectetur nisi, ab beatae suscipit voluptate omnis sapiente rerum aspernatur nihil? Hic, voluptatibusMagni, perspiciatis odit! Dignissimos ullam porro eligendi architecto tenetur, cum placeat? Vitae, deserunt totam reiciendis eligendi neque aliquid quos voluptates odit eius. Expedita explicabo libero veritatis id soluta? Obcaecati, voluptatem Mollitia odit fuga quis eos necessitatibus alias commodi ducimus aliquid, eveniet in cumque sint nihil. Aperiam repudiandae consequatur quis iste saepe incidunt mollitia modi debitis illum corrupti nesciunt, atquQuaerat rerum odit, adipisci ipsam a molestiae totam amet nisi omnis voluptatum deleniti quia hic dolore corrupti tenetur veniam quos? Aliquid voluptatibus facilis excepturi modi non in neque deserunt a Sed aut consequuntur fugiat earum, ipsam dolorem autem architecto voluptatibus error, officia neque at incidunt perferendis nobis officiis labore esse veritatis cumque tempora laboriosam ratione, expedita quasi eos. Soluta, dolore Labore nemo ea, commodi ducimus veritatis veniam asperiores expedita porro corrupti consequatur sed! Cum provident vero alias molestias repudiandae iure, asperiores, maxime cupiditate ullam similique reprehenderit. Aut corporis ipsa tempora!"
    },
    {
        title: "Gardening Tips",
        date: "August 2024",
        cover: "img/garden.jpeg",
        description: "Cultivate your green thumb with these tips. Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus enim libero explicabo sit, aperiam sed dolores pariatur ea asperiores dolore, reiciendis consequuntur maiores perspiciatis vel perferendis nobis, exercitationem excepturi magni Labore quam quis cumque doloribus expedita hic aspernatur in? Voluptatum molestiae, modi aperiam veritatis odio dolore rerum animi voluptas quo ducimus expedita, quod delectus quidem magni. Ea autem facere consectetu Perferendis magni, assumenda sequi, similique tempore odit nulla suscipit quo molestiae consectetur dicta repudiandae aliquam, soluta facere vero! Eligendi, tempore enim repellendus impedit sunt quaerat quam illum minus officia vero Tempora corporis quas ab illum, ipsam dolore expedita labore! Perferendis consectetur a necessitatibus, est dicta, provident maxime ipsam aut rerum autem voluptate accusamus! Ex illum inventore saepe, molestias autem doloremqueIpsam corporis deserunt tempora optio nostrum officia tempore mollitia totam impedit numquam consectetur, vel harum nisi blanditiis, porro sint maxime ipsum. Ad suscipit perferendis ea assumenda exercitationem enim eum dolorumSed voluptate ut laudantium, ducimus fugiat, expedita aut, incidunt tenetur aliquam alias ipsa. Atque, iste a eius, aspernatur vero, sunt perferendis natus eligendi accusantium praesentium quo id expedita soluta molestiasCorrupti quisquam dignissimos beatae dolores eligendi exercitationem sapiente cum ratione qui? Facere commodi quis esse aperiam iste consectetur nisi, ab beatae suscipit voluptate omnis sapiente rerum aspernatur nihil? Hic, voluptatibusMagni, perspiciatis odit! Dignissimos ullam porro eligendi architecto tenetur, cum placeat? Vitae, deserunt totam reiciendis eligendi neque aliquid quos voluptates odit eius. Expedita explicabo libero veritatis id soluta? Obcaecati, voluptatem Mollitia odit fuga quis eos necessitatibus alias commodi ducimus aliquid, eveniet in cumque sint nihil. Aperiam repudiandae consequatur quis iste saepe incidunt mollitia modi debitis illum corrupti nesciunt, atquQuaerat rerum odit, adipisci ipsam a molestiae totam amet nisi omnis voluptatum deleniti quia hic dolore corrupti tenetur veniam quos? Aliquid voluptatibus facilis excepturi modi non in neque deserunt a Sed aut consequuntur fugiat earum, ipsam dolorem autem architecto voluptatibus error, officia neque at incidunt perferendis nobis officiis labore esse veritatis cumque tempora laboriosam ratione, expedita quasi eos. Soluta, dolore Labore nemo ea, commodi ducimus veritatis veniam asperiores expedita porro corrupti consequatur sed! Cum provident vero alias molestias repudiandae iure, asperiores, maxime cupiditate ullam similique reprehenderit. Aut corporis ipsa tempora"
    },
    {
        title: "Art & Culture",
        date: "September 2024",
        cover: "img/art.jpeg",
        description: "Explore the world of art and culture. Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus enim libero explicabo sit, aperiam sed dolores pariatur ea asperiores dolore, reiciendis consequuntur maiores perspiciatis vel perferendis nobis, exercitationem excepturi magni Labore quam quis cumque doloribus expedita hic aspernatur in? Voluptatum molestiae, modi aperiam veritatis odio dolore rerum animi voluptas quo ducimus expedita, quod delectus quidem magni. Ea autem facere consectetu Perferendis magni, assumenda sequi, similique tempore odit nulla suscipit quo molestiae consectetur dicta repudiandae aliquam, soluta facere vero! Eligendi, tempore enim repellendus impedit sunt quaerat quam illum minus officia vero Tempora corporis quas ab illum, ipsam dolore expedita labore! Perferendis consectetur a necessitatibus, est dicta, provident maxime ipsam aut rerum autem voluptate accusamus! Ex illum inventore saepe, molestias autem doloremqueIpsam corporis deserunt tempora optio nostrum officia tempore mollitia totam impedit numquam consectetur, vel harum nisi blanditiis, porro sint maxime ipsum. Ad suscipit perferendis ea assumenda exercitationem enim eum dolorumSed voluptate ut laudantium, ducimus fugiat, expedita aut, incidunt tenetur aliquam alias ipsa. Atque, iste a eius, aspernatur vero, sunt perferendis natus eligendi accusantium praesentium quo id expedita soluta molestiasCorrupti quisquam dignissimos beatae dolores eligendi exercitationem sapiente cum ratione qui? Facere commodi quis esse aperiam iste consectetur nisi, ab beatae suscipit voluptate omnis sapiente rerum aspernatur nihil? Hic, voluptatibusMagni, perspiciatis odit! Dignissimos ullam porro eligendi architecto tenetur, cum placeat? Vitae, deserunt totam reiciendis eligendi neque aliquid quos voluptates odit eius. Expedita explicabo libero veritatis id soluta? Obcaecati, voluptatem Mollitia odit fuga quis eos necessitatibus alias commodi ducimus aliquid, eveniet in cumque sint nihil. Aperiam repudiandae consequatur quis iste saepe incidunt mollitia modi debitis illum corrupti nesciunt, atquQuaerat rerum odit, adipisci ipsam a molestiae totam amet nisi omnis voluptatum deleniti quia hic dolore corrupti tenetur veniam quos? Aliquid voluptatibus facilis excepturi modi non in neque deserunt a Sed aut consequuntur fugiat earum, ipsam dolorem autem architecto voluptatibus error, officia neque at incidunt perferendis nobis officiis labore esse veritatis cumque tempora laboriosam ratione, expedita quasi eos. Soluta, dolore Labore nemo ea, commodi ducimus veritatis veniam asperiores expedita porro corrupti consequatur sed! Cum provident vero alias molestias repudiandae iure, asperiores, maxime cupiditate ullam similique reprehenderit. Aut corporis ipsa tempora!"
    }
];

function displayMagazines() {
    const magazineContainer = document.getElementById('magazineContainer');
    magazineContainer.innerHTML = '';

    magazines.forEach(magazine => {
        const magazineDiv = document.createElement('div');
        magazineDiv.className = 'magazine';
        magazineDiv.innerHTML = `
            <img src="${magazine.cover}" alt="${magazine.title}">
            <h3>${magazine.title}</h3>
            <p>${magazine.date}</p>
        `;
        magazineDiv.onclick = () => openModal(magazine);
        magazineContainer.appendChild(magazineDiv);
    });
}

function openModal(magazine) {
    document.getElementById('modalTitle').innerText = magazine.title;
    document.getElementById('modalDescription').innerText = magazine.description;
    document.getElementById('magazineModal').style.display = "block";
}

function closeModal() {
    document.getElementById('magazineModal').style.display = "none";
}

function searchMagazines() {
    const input = document.getElementById('search').value.toLowerCase();
    const filteredMagazines = magazines.filter(magazine =>
        magazine.title.toLowerCase().includes(input) ||
        magazine.date.toLowerCase().includes(input)
    );
    const magazineContainer = document.getElementById('magazineContainer');
    magazineContainer.innerHTML = '';

    filteredMagazines.forEach(magazine => {
        const magazineDiv = document.createElement('div');
        magazineDiv.className = 'magazine';
        magazineDiv.innerHTML = `
            <img src="${magazine.cover}" alt="${magazine.title}">
            <h3>${magazine.title}</h3>
            <p>${magazine.date}</p>
        `;
        magazineDiv.onclick = () => openModal(magazine);
        magazineContainer.appendChild(magazineDiv);
    });
}

// Initial display of magazines
displayMagazines();